create table if not exists public.sc2026 (
  id bigint generated by default as identity primary key,
  source_row integer not null unique,
  color_group text not null default '투명or흰색',
  color_code text,
  payload jsonb not null default '{}'::jsonb,
  app_package text generated always as (payload ->> '앱패키지명') stored,
  opt_code text generated always as (payload ->> '옵션값(OPT_CODE)') stored,
  subject_code text generated always as (payload ->> '전체과목코드') stored,
  subject_name text generated always as (payload ->> '전체과목명') stored,
  lesson_name text generated always as (payload ->> '차시명') stored,
  menu_name text generated always as (payload ->> '목차명') stored,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists sc2026_payload_gin on public.sc2026 using gin (payload);
create index if not exists sc2026_subject_code_idx on public.sc2026 (subject_code);
create index if not exists sc2026_opt_code_idx on public.sc2026 (opt_code);
create index if not exists sc2026_color_group_idx on public.sc2026 (color_group);

create or replace function public.set_sc2026_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sc2026_updated_at on public.sc2026;
create trigger trg_sc2026_updated_at
before update on public.sc2026
for each row
execute function public.set_sc2026_updated_at();

alter table public.sc2026 enable row level security;

drop policy if exists "Allow anon read sc2026" on public.sc2026;
create policy "Allow anon read sc2026"
on public.sc2026
for select
to anon
using (true);

drop policy if exists "Allow anon insert sc2026" on public.sc2026;
create policy "Allow anon insert sc2026"
on public.sc2026
for insert
to anon
with check (true);

drop policy if exists "Allow anon update sc2026" on public.sc2026;
create policy "Allow anon update sc2026"
on public.sc2026
for update
to anon
using (true)
with check (true);

create table if not exists public.sc2026_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

drop trigger if exists trg_sc2026_settings_updated_at on public.sc2026_settings;
create trigger trg_sc2026_settings_updated_at
before update on public.sc2026_settings
for each row
execute function public.set_sc2026_updated_at();

alter table public.sc2026_settings enable row level security;

drop policy if exists "Allow anon read sc2026 settings" on public.sc2026_settings;
create policy "Allow anon read sc2026 settings"
on public.sc2026_settings
for select
to anon
using (true);

drop policy if exists "Allow anon insert sc2026 settings" on public.sc2026_settings;
create policy "Allow anon insert sc2026 settings"
on public.sc2026_settings
for insert
to anon
with check (true);

drop policy if exists "Allow anon update sc2026 settings" on public.sc2026_settings;
create policy "Allow anon update sc2026 settings"
on public.sc2026_settings
for update
to anon
using (true)
with check (true);
